App.js, index.js, package.json, src/App.js, src/ChooseDialect.js, yarn.lock
Set up expo, install styled component and react native paper. Worked on listing hard coded dialects.
=> List hougen

App.js, index.js, package.json, src/ChooseDialect.js, src/Lesson.js, yarn.lock
This PR creates a blank lesson page.
The important part of this PR was adding navigation.
Followed the instructions here: https://reactnavigation.org/docs/getting-started
Be sure to `yarn install` after this gets merged in.
Installed the following with expo `expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view`
=> Lesson page

App.js, src/components/ChooseDialect.js, src/components/Lesson.js, src/components/PatternList.js, src/shared/ScreenLayout.js
Added navigations between ChooseDirect, PatternList, and Lesson pages. 
Listed hard coded patterns in PatternList component. Each list can be tapped using TouchableHighlight and logs tapped pattern.
=> Pattern list

src/components/ChooseDialect.js
Add navigation and layout in ChooseDirect
=> add layout and navigation in ChooseDialect

App.js, package.json, src/components/ChooseDialect.js, src/rdx/actions/index.js, src/rdx/actions/types.js, src/rdx/reducers/dialectReducer.js, src/rdx/reducers/index.js, src/rdx/store/index.js, yarn.lock
Set up redux and connects to api to get dialects data.
=> Connect to api

src/components/ChooseDialect.js, src/components/Lesson.js, src/components/PatternList.js
Passes selected dialects, grammars, and examples to different components with navigation. Displays grammars and examples.
=> Show grammars

src/components/ChooseDialect.js, src/shared/SoundPlayButton.js
Selected dialect has background color. When it's double tapped navigates toPatternList page.
Also add navigateBtn function that navigates to PatternList.
=> Double tap

src/components/PatternList.js
In PatternList page when selecting grammar it changes the background color, and after that it navigates to Lesson page by clicking next button.
When grammar is not selected, alert shows up.
Also double tapping grammar navigates to Lesson page.
https://www.loom.com/share/3ba25430a8934cb284ebe4687c9af5c7
=> Double tap pattern list

src/components/ChooseDialect.js, src/components/PatternList.js
Added "Lesson #" in PatternList page. Changed page title to selected dialect.
=> Display lesson in pattern list

src/shared/SoundPlayButton.js
Changes the color of play audio icon when it is clicked
https://www.loom.com/share/9806ba5aa0a14cb3bc9921dcba9ec4da
=> Changes the color of play audio icon when it is clicked

src/components/Lesson.js
Added navigation to next Lesson page or go back to PatternList by clicking complete button.
https://www.loom.com/share/79fafa0aa1f14e9dbfa860a879f37d4d
=> Added navigation to next Lesson page or go back to PatternList

src/shared/ScreenLayout.js
Fixed height on other device using demension.
=> fix height on other device

.gitignore, src/components/ChooseDialect.js, src/components/PatternList.js
change font color when selected
[
](url)
=> change font color when selected

src/components/Loading.js, src/shared/ScreenLayout.js, src/shared/SoundPlayButton.js
=> Fixes audio, and some other warnings and errors showing up

src/components/ChooseDialect.js, src/components/Loading.js, src/components/PatternList.js, src/components/helpers/FindById.js
Added FindById as a helper method.
=> add FindById as a helper method

src/components/PatternList.js
=> fix an issue with FindById

src/components/ChooseDialect.js, src/components/Lesson.js, src/components/PatternList.js, src/rdx/actions/index.js, src/rdx/reducers/completedGrammarsReducer.js
Added ProgressIcon with text and shows completed number of lessons.
=> add ProgressIcon with text

src/components/ChooseDialect.js, src/shared/ScreenLayout.js
Fixed layout and added Honma header in each page.
=> fix layout and add Honma header in each page

src/components/Lesson.js, src/shared/SoundPlayButton.js
Changed layout in lesson page.
=> Redesign lesson page

src/components/Commonness.js, src/components/Lesson.js
Layout is fixed when displaying completed date. Added commonness and displays stars.
=> display commonness stars and fix layout

src/components/Lesson.js, src/shared/SoundPlayButton.js
This fixed SoundPlayButton style and added scroll view in Lesson page.
=> fix SoundPlayButton style and add scroll view in Lesson page

src/components/Commonness.js, src/components/Lesson.js, src/components/Quiz.js
Added quiz button to show quiz in Lesson page. It hides when you leave the page.
https://www.loom.com/share/226eccde4e724d7ea3a5492c72a3a38b
=> Show quiz button

src/components/ChooseDialect.js, src/components/Lesson.js, src/components/PatternList.js, src/components/Quiz.js, src/shared/FooterButton.js, src/shared/ScreenLayout.js
This PR changed the styling for the footer button to display both English and Japanese text.
Also it will save the completed time when the user presses the check answer button with correct answer. The footer button in Lesson page only navigates to the next lesson page now.
Finally it hides the footer button in the lesson page when the user has not completed the quiz.
https://www.loom.com/share/7c62396416ca4acca00fb2390d0da507
=> Show next lesson button

package.json, src/components/Lesson.js, yarn.lock
Added a package to scroll the screen up when keyboard shows up.
Before:
After:
https://www.loom.com/share/9ec0fe09bc0c4259a4565499dce002ff
=> Added a package to scroll the screen up when keyboard shows up

src/components/ChooseDialect.js, src/components/Modal.js, src/components/ModalContents.js, src/shared/ScreenLayout.js
In this PR it allows the user to select the icon and show the Modal. Modal toggles too.
https://www.loom.com/share/b6834ed07ee04ec786aa0236e7a3e34f
=> Set modal container

src/components/ChooseDialect.js, src/components/PatternList.js, src/shared/ScreenLayout.js
Fixed footer button bug when the user completes the quiz.
=> fix footer_btn_bug

App.js, src/components/Registration.js, src/components/Signin.js, src/components/Signup.js
Added navigations from Registration page to sign in/ sign up pages. Added styling.
https://www.loom.com/share/8ddea8322a68400f8a3b6bd7b4073c08
=> User login page

src/components/Signin.js, src/components/Signup.js, src/rdx/actions/index.js, src/rdx/actions/types.js, src/rdx/reducers/authReducer.js
Shows error messages if errors. Navigates the user to loading page when successfully signing up.
https://www.loom.com/share/b49cbd540d984e0d9baad1b87b61f557?sharedAppSource=personal_library
=> Sends request to sign up.

src/components/ChooseDialect.js, src/components/Lesson.js, src/components/Loading.js, src/components/PatternList.js, src/components/Quiz.js, src/components/Signin.js, src/components/Signup.js, src/rdx/actions/index.js, src/rdx/actions/types.js, src/rdx/reducers/authReducer.js
It updates quiz_completed in rails when quiz is completed.
Shows progress of quizzes, checkmark, completed at from both rails and redux.
=> Quiz complete

src/components/ChooseDialect.js, src/components/ModalContents.js
This PR displays a selected dialect's info in modal with its default picture and description.
Added category buttons in the modal, will work on this functionality in other ticket.
https://user-images.githubusercontent.com/60206746/148016824-e27b7b8e-24ac-4d6a-a6d3-eecf06c0077a.mov
=> Show descriptions and default images in modal

package.json, src/components/ChooseDialect.js, src/components/Loading.js, src/components/PlaceInfoDetail.js, src/components/PlaceInfoList.js, src/components/PlaceInfoMain.js, src/components/Quiz.js, src/components/Signin.js, src/components/Signup.js, yarn.lock
We need to add contents and navigation in place info detail page.
https://user-images.githubusercontent.com/60206746/160312394-de42d9be-25b9-4017-b860-ec9a19d10561.mp4
N/A
=> Contents and navigation in place info detail page

package.json, src/components/ChooseDialect.js, src/components/PatternList.js, yarn.lock
Need to use new apis in Loading and ChooseDialect page.
Implemented new apis.
[Card-43](https://trello.com/c/lZd50E3X)
=> [Card-43] use new apis

package.json, src/components/Lesson.js, src/components/PatternList.js, src/components/Quiz.js, src/test/__snapshots__/quiz.test.js.snap, src/test/quiz.test.js, src/test/test-data/quiz-test-data.js, yarn.lock
We need to show a different quiz if any after completing a quiz.
https://github.com/cheemurakami/honma-mobile/assets/60206746/7a5b596c-df8a-4214-bdcd-c01aa2615633
Need to display:
- Display the quiz number like Q1:
- Btn copy change
- Record the completions of the grammar
- If completed all the quizzes, show the “Next lesson” button in footer
- If all quizzes are completed update the completion lesson card in grammar(lesson) page
If all quizzes are completed update the completion lesson card in dialect page
[Card 46](https://trello.com/c/6NE74jwe)
=> [Card 46] Show more quizzes

src/components/Lesson.js, src/test/__snapshots__/lesson.test.js.snap, src/test/lesson.test.js, src/test/test-data/lesson-test-data.js
If a user has completed all the quizzes, show completed at otherwise hide it.
Removed redux and changes are applied.
https://github.com/cheemurakami/honma-mobile/assets/60206746/7e5c4173-e4f2-4de3-b790-8a94ab62a6ee
[Card 47](https://trello.com/c/gxsvg0W7)
=> [Card 47] Display completed at correctly

App.js, src/components/Dialects.js, src/components/LessonProgressCard.js, src/components/Loading.js, src/components/PatternList.js, src/test/__snapshots__/lesson-progress-card.test.js.snap, src/test/lesson-progress-card.test.js, src/test/test-data/lesson-test-data.js
It should show the correct completed lesson number.
Applied changes.
[Card 48](https://trello.com/c/M9dRaeEL)
=> [Card 48] Show correct completed lesson numbers
